all_species = [
        'Adelotus brevis',
        'Crinia parinsignifera',
        'Crinia signifera',
        'Crinia tinnula',
        'Heleioporus australiacus',
        'Limnodynastes dumerilii',
        'Limnodynastes peronii',
        'Limnodynastes tasmaniensis',
        'Litoria aurea',
        'Litoria brevipalmata',
        'Litoria caerulea',
        'Litoria chloris',
        'Litoria citropa',
        'Litoria ewingii',
        'Litoria fallax',
        'Litoria freycineti',
        'Litoria gracilenta',
        'Litoria jervisiensis',
        'Litoria latopalmata',
        'Litoria lesueuri',
        'Litoria littlejohni',
        'Litoria nasuta',
        'Litoria nudidigitus',
        'Litoria peronii',
        'Litoria phyllochroa',
        'Litoria quiritatus',
        'Litoria revelata',
        'Litoria rubella',
        'Litoria tyleri',
        'Litoria verreauxii',
        'Litoria wilcoxii',
        'Mixophyes fasciolatus',
        'Mixophyes iteratus',
        'Paracrinia haswelli',
        'Platyplectrum ornatum',
        'Pseudophryne australis',
        'Pseudophryne bibronii',
        'Pseudophryne coriacea',
        'Uperoleia fusca',
        'Uperoleia laevigata',
        'Uperoleia mahonyi',
        'Uperoleia tyleri'
]

label_options = [
'✨ Empty',
'🦗 Insect',
'🦜 Bird',
'🐕 Dog',
'🧒🏽 Human',
'🚙 Car',
'💧 Water',
'💨 Wind'
]

path = 'data/3s/'